FROM python:3.11-slim as builder
WORKDIR /code
RUN pip install --upgrade pip
RUN pip install poetry
COPY poetry.lock /code/poetry.lock
COPY pyproject.toml /code/pyproject.toml
RUN poetry export -f requirements.txt -o /code/requirements.txt --without-hashes

FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY --from=builder /code/requirements.txt /code/requirements.txt
# パッケージリストの更新
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libc6-dev \
    libpq-dev \
    gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY ./app /code/app
# COPY ./docs /code/docs

# migration (開発用)
# COPY ./migrations /code/migrations
# COPY ./alembic.ini /code/alembic.ini

# env
ENV PYTHONPATH=/code/app

EXPOSE 8000
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
