version: "3.0"

services:
  api:
    container_name: api
    volumes:
      - .:/code/
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - fastapi_network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - fastapi_network

volumes:
  postgres:

networks:
  fastapi_network:
