version: "3.0"

services:
  api_fastapi:
    container_name: api_fastapi
    volumes:
      - .:/code/
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - fastapi_network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - fastapi_network

volumes:
  postgres:

networks:
  fastapi_network:
